# Generated by Django 6.0.7 on 2026-07-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('centroid', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clusters',
            },
        ),
        migrations.CreateModel(
            name='EmbeddedArticles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stories.clusters')),
            ],
            options={
                'db_table': 'embedded_articles',
            },
        ),
    ]
