# Generated by Django 6.0.7 on 2026-07-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bias', models.FloatField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
