# Generated by Django 6.0.7 on 2026-07-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedarticles',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stories.publisher'),
        ),
    ]
