# Generated by Django 6.0.7 on 2026-07-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_embeddedarticles_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='domain',
        ),
    ]
