# Generated by Django 6.0.7 on 2026-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_remove_publisher_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
