# Generated by Django 6.0.7 on 2026-08-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_publisher_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
