# Generated by Django 6.0.7 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_clusters_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='ai_summary',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='embeddedarticles',
            name='article_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clusters',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
