# Generated by Django 6.0.7 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_clusters_ai_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
