# Generated by Django 6.0.7 on 2026-08-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_clusters_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusters',
            name='title',
        ),
    ]
