# Generated by Django 6.0.7 on 2026-08-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_remove_clusters_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='title',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
