# Generated by Django 6.0.7 on 2026-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_clusters_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
