# Generated by Django 6.0.7 on 2026-08-22 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_clusters_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
    ]
