# Generated by Django 6.0.7 on 2026-08-23 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_clusters_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True),
        ),
    ]
